artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/DoomedMean/Machine-Learning/raw/main/Text%20Summarization/raw/summarizer-data.zip # download data
  local_data_file: artifacts/data_ingestion/data.zip # save as data.zip
  unzip_dir: artifacts/data_ingestion # unzip file

  
data_validation:
  root_dir: artifacts/data_validation
  Status_File: artifacts/data_validation/status.txt
  All_Required_File: ["train", "test", "validation"]


data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/samsum_dataset
  tokenizer_name: google/pegasus-cnn_dailymail

model_trainer:
  root_dir: artifacts/model_trainer
  data_path: artifacts/data_transformation/samsum_dataset
  model_ckpt: google/pegasus-cnn_dailymail